jobs:
  - job: lightrail
    pool: server
    steps:
      - task: odefun.odsp-lightrail-tasks-partner.odsp-lightrail-tasks-SizeAuditorWorker.SizeAuditorWorker@0
        displayName: 'Size Auditor Check on LightRail'
        inputs:
          connectedServiceName: lowimpact
          sourceVersionMessage: '$(Build.SourceVersionMessage)'
          sourceRepositoryUrl: 'https://github.com/ecraig12345-test-org/fluentui'
