pr:
  - master

trigger:
  - master

pool: 'Self Host Ubuntu'

jobs:
  - job: Build
    steps:
      - template: azure-pipelines.tools.yml

      - script: yarn
        displayName: yarn

      - script: yarn buildto test-bundles
        displayName: yarn build to test-bundles

      - script: yarn workspace test-bundles bundle:size
        displayName: yarn bundle test-bundles
      # - script: yarn workspace office-ui-fabric-react just webpack
      #   displayName: yarn bundle OUFR
